# Data Ingestion to MongoDB

In [155]:
from pymongo import MongoClient
from pymongo.operations import SearchIndexModel
import pandas as pd
import math

## Load Observations and Wind Power Data

In [58]:
obs = pd.read_csv("./data/meteorological_data.csv", encoding = "ISO-8859-1")

In [60]:
wp = pd.read_csv("./data/wind_power_generation_data.csv", encoding = "ISO-8859-1")

In [62]:
obs.head(10)

,day,start time 3h interval (utc),location,height above ground in m,u-component wind in m/s,v-component wind in m/s,temperature in °C,global surface radiation in W/m2
0,1,00:00,1,2,5.00,-0.30,1.65,0.0
1,1,03:00,1,2,8.22,-1.20,1.45,2.0
2,1,06:00,1,2,5.36,-2.91,0.65,170.0
3,1,09:00,1,2,6.94,-3.17,1.55,350.0
4,1,12:00,1,2,6.58,-2.26,2.95,570.0
5,1,15:00,1,2,7.28,-1.95,2.85,368.0
6,1,18:00,1,2,2.70,0.12,-0.25,0.0
7,1,21:00,1,2,3.66,0.45,0.25,0.0
8,2,00:00,1,2,5.14,1.70,1.05,0.0
9,2,03:00,1,2,7.23,1.91,1.45,2.0

In [64]:
obs.dtypes

day                                   int64
start time 3h interval (utc)         object
location                              int64
height above ground in m              int64
u-component wind in m/s             float64
v-component wind in m/s             float64
temperature in °C                   float64
global surface radiation in W/m2    float64
dtype: object

In [66]:
wp.head()

   day start time quarter hour  wind generation in MW
0    1                   00:00                 146.15
1    1                   00:15                 126.28
2    1                   00:30                 121.11
3    1                   00:45                 121.32
4    1                   01:00                 123.91

In [68]:
wp.dtypes

day                          int64
start time quarter hour     object
wind generation in MW      float64
dtype: object

## Data Iteration

* Let's iterate each time point in each measurement points and also historical points to day backward
* Then we'll combine those information to one data row
* And then we'll add total wind power time series to that row
* Finally we'll take time point, wind power time series and calculate the vector to that data row and store it to dataframe

In [137]:
#TODO: Sensitive Data
CONNECTION_STRING = "mongodb+srv://aiinaction:Klondyke1234@starteconcluster1.cg9gxnb.mongodb.net/?retryWrites=true&w=majority&appName=StarteconCluster1"

In [139]:
client = MongoClient(CONNECTION_STRING)

In [141]:
databases = client.list_database_names()
databases

['EcoWind', 'admin', 'local']

In [143]:
db = client[databases[0]]

In [145]:
db.list_collection_names()

['wind_power_generation_data_05042017_competition',
 'wind_power_generation_data_04042017_competition',
 'meteorological_data_04042017_competition',
 'wind_power_generation_data_07042017_competition',
 'wind_power_generation_data_15042017_competition',
 'wind_power_generation_data_10042017_competition',
 'meteorological_data_10042017_competition',
 'meteorological_data_14042017_competition',
 'meteorological_data_12042017_competition',
 'wind_power_generation_data_08042017_competition',
 'wind_power_generation_data_06042017_competition',
 'meteorological_data_09042017_competition',
 'wind_power_generation_data_03042017_competition',
 'measurements',
 'meteorological_data_13042017_competition',
 'meteorological_data',
 'meteorological_data_15042017_competition',
 'wind_power_generation_data_13042017_competition',
 'meteorological_data_16042017_competition',
 'meteorological_data_07042017_competition',
 'wind_power_generation_data_11042017_competition',
 'wind_power_generation_data_09042017_competition',
 'meteorological_data_08042017_competition',
 'wind_power_generation_data_16042017_competition',
 'wind_power_generation_data_14042017_competition',
 'meteorological_data_03042017_competition',
 'meteorological_data_06042017_competition',
 'meteorological_data_11042017_competition',
 'wind_power_generation_data',
 'wind_power_generation_data_12042017_competition']

In [147]:
coll = db["observations_wind_power_vectors"]

In [71]:
#hist 
days = 365 # full 1-366, but we'll leave padding
timepoints = ["00:00","03:00","06:00", "09:00","12:00","15:00","18:00","21:00"] # 3 hours periods along the day
altitudes = [2, 80, 100] # 2 meters,80 meters, 100 meters

In [73]:
[timepoints[x] for x in range(len(timepoints))]

['00:00', '03:00', '06:00', '09:00', '12:00', '15:00', '18:00', '21:00']

In [75]:
def df_to_vector(df, d, t, tp):
    df2 = df[
                (df["start time 3h interval (utc)"] == tp[t]) & 
                (df["day"] == d)
            ]
    arr = []
    arr.extend(df2["u-component wind in m/s"].to_list())
    arr.extend(df2["v-component wind in m/s"].to_list())
    arr.extend(df2["temperature in °C"].to_list())
    arr.extend(df2["global surface radiation in W/m2"].to_list())

    return arr

In [77]:
def get_history_point(h, d, t):
    if (t-h > -1):
        return d, t
    else:
        f = math.floor((h-1)/8)+1
        return d-f, f*8+(t-h)

In [149]:
id = 1
for d in range(2, days):
    for t in range(len(timepoints)):
        vectors = []
        # time 0
        vectors = vectors + df_to_vector(obs, d, t, timepoints)
        # time-1 to time-5
        for h in range(1,6): 
            d1, t1 = get_history_point(h, d, t)
            vectors = vectors + df_to_vector(obs, d1, t1, timepoints)

        # wind power time series
        if (t > len(timepoints)-2):
            t1 = 0
            d1 = d + 1
        else:
            t1 = t + 1
            d1 = d
            
        df = wp[
                (wp["day"].astype(str).str.zfill(3)+":"+wp["start time quarter hour"].astype(str) >= str(d).zfill(3)+":"+timepoints[t]) & 
                (wp["day"].astype(str).str.zfill(3)+":"+wp["start time quarter hour"].astype(str) < str(d1).zfill(3)+":"+timepoints[t1])
            ]
        windpower = df["wind generation in MW"].to_list()

        item = {
          "id" : id,
          "date" : str(str(d).zfill(3)+":"+timepoints[t]),
          "vectors" : vectors,
          "windpower" : windpower,
        }
        coll.insert_one(item)
        id = id + 1

In [151]:
item_details = coll.find()
for item in item_details:
    print(item)
    break

{'_id': ObjectId('68542d38b697aace7840ee8f'), 'id': 1, 'date': '002:00:00', 'vectors': [5.14, 11.0, 11.8, 3.48, 6.9, 7.8, 8.24, 13.3, 14.0, 5.85, 10.5, 11.2, 6.51, 11.1, 11.8, 4.1, 6.4, 6.8, 3.78, 10.3, 11.2, 6.08, 10.1, 10.8, 4.59, 8.1, 8.6, 5.17, 10.5, 11.3, 1.7, 2.8, 2.9, 3.5, 5.2, 5.5, -0.5, -1.3, -1.5, 3.8, 5.1, 5.2, 1.9, 2.6, 2.7, 3.9, 4.9, 4.9, 2.8, 5.4, 5.7, 2.7, 3.6, 3.7, 2.4, 3.2, 3.2, 1.8, 2.5, 2.6, 1.05, 1.15, 1.05, 1.35, 1.35, 1.35, 2.45, 2.55, 2.45, 1.65, 1.75, 1.65, 4.65, 4.55, 4.35, 2.65, 2.05, 1.95, 0.35, 0.45, 0.35, 0.45, 0.75, 0.65, 0.15, 0.35, 0.35, 1.25, 0.95, 0.85, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.66, 9.45, 10.3, 3.6, 7.13, 8.0, 9.24, 14.02, 14.7, 9.25, 13.64, 14.4, 6.15, 11.28, 12.0, 6.8, 10.71, 11.2, 4.49, 11.22, 12.2, 9.35, 13.07, 13.6, 8.4, 12.56, 13.2, 4.97, 10.88, 11.7, 0.45, 0.4, 0.3, 2.66, 3.4, 3.5, -1.58, -2.9, -3.1, 1.58, 2.0, 2.0, 1.9, 2.2, 2.1, 1.83, 2.0, 2.0, 0.84, 1.2, 1.2, -1.52, -1.9, -2.1, 0.19, -0.1, -0.3, -0.2, -1.1, -1.3, 0.25, 1.15, 1.05, 1.05, 1.75, 1.85, 1.75, 1.85, 1.75, 1.45, 1.75, 1.65, 3.25, 3.65, 3.65, 2.85, 2.95, 2.75, -0.25, 0.15, 0.15, 2.05, 1.95, 1.75, 1.65, 2.05, 1.95, 0.05, 0.45, 0.35, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.7, 6.6, 7.3, 2.69, 5.5, 6.1, 6.11, 11.1, 11.8, 6.03, 10.3, 11.0, 3.37, 7.2, 7.9, 6.97, 10.7, 11.2, 2.81, 8.4, 9.7, 5.95, 9.9, 10.4, 5.21, 8.7, 9.3, 4.17, 9.7, 10.5, 0.12, -0.8, -1.1, 0.58, 0.2, 0.0, -1.19, -2.8, -3.1, 0.82, 0.3, 0.2, -0.01, -0.6, -0.7, 0.91, 0.3, 0.1, 0.19, -0.2, -0.5, 1.73, 1.5, 1.4, -0.47, -1.0, -1.1, -0.5, -2.0, -2.4, -0.25, 0.95, 0.85, 1.95, 2.95, 2.85, 2.05, 2.45, 2.35, 1.25, 1.95, 1.85, 3.65, 4.85, 4.85, 3.55, 3.35, 3.15, -0.35, 0.35, 0.25, 2.35, 2.75, 2.65, 2.65, 3.55, 3.55, 0.15, 0.55, 0.45, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 7.28, 11.41, 11.87, 7.72, 10.79, 11.06, 10.99, 14.61, 15.07, 10.48, 15.5, 15.94, 9.14, 14.45, 14.92, 8.85, 11.31, 11.55, 6.31, 13.78, 14.38, 10.85, 15.72, 16.22, 11.36, 14.6, 15.05, 7.82, 13.49, 14.02, -1.95, -3.17, -3.3, -1.52, -2.17, -2.2, -3.94, -5.4, -5.6, -1.87, -3.09, -3.2, -3.5, -5.31, -5.5, -5.27, -6.48, -6.6, -0.62, -1.64, -1.7, -3.35, -4.85, -5.1, -6.37, -7.78, -8.1, -1.79, -3.49, -3.7, 2.85, 1.85, 1.65, 3.45, 3.05, 2.95, 5.05, 4.25, 4.05, 3.45, 3.15, 2.95, 4.85, 4.55, 4.45, 6.65, 5.45, 5.25, 1.85, 1.75, 1.55, 6.05, 5.55, 5.45, 7.05, 5.95, 5.75, 3.45, 2.85, 2.65, 368.0, 368.0, 368.0, 355.0, 355.0, 355.0, 327.0, 327.0, 327.0, 356.0, 356.0, 356.0, 311.0, 311.0, 311.0, 352.0, 352.0, 352.0, 325.0, 325.0, 325.0, 319.0, 319.0, 319.0, 233.0, 233.0, 233.0, 337.0, 337.0, 337.0, 6.58, 9.7, 10.0, 7.13, 9.4, 9.6, 10.33, 13.8, 14.1, 8.49, 11.5, 11.8, 7.8, 10.8, 11.2, 9.47, 11.8, 12.0, 4.51, 9.8, 10.2, 10.5, 13.6, 13.9, 10.59, 13.3, 13.6, 6.04, 9.9, 10.2, -2.26, -3.4, -3.6, -1.64, -2.3, -2.4, -3.59, -4.8, -4.9, -0.99, -1.7, -1.7, -0.31, -0.9, -1.0, -4.96, -6.7, -6.9, -0.98, -2.2, -2.2, -2.7, -3.9, -4.1, -3.14, -4.4, -4.5, -0.91, -2.0, -2.1, 2.95, 1.45, 1.25, 2.85, 2.25, 2.05, 4.95, 3.85, 3.65, 3.75, 2.85, 2.65, 4.45, 3.55, 3.35, 7.15, 5.55, 5.35, 3.45, 2.35, 2.05, 6.15, 5.05, 4.85, 6.55, 5.15, 4.95, 4.65, 3.15, 2.95, 570.0, 570.0, 570.0, 580.0, 580.0, 580.0, 520.0, 520.0, 520.0, 570.0, 570.0, 570.0, 450.0, 450.0, 450.0, 550.0, 550.0, 550.0, 520.0, 520.0, 520.0, 520.0, 520.0, 520.0, 320.0, 320.0, 320.0, 550.0, 550.0, 550.0, 6.94, 11.13, 11.55, 8.19, 11.78, 12.04, 12.63, 16.26, 16.66, 11.48, 15.71, 16.11, 8.85, 13.61, 14.0, 12.38, 15.44, 15.75, 6.63, 13.01, 13.57, 10.74, 14.12, 14.47, 11.65, 14.99, 15.33, 8.22, 13.63, 14.17, -3.17, -5.2, -5.4, -2.37, -3.17, -3.26, -4.63, -5.79, -5.96, -3.09, -4.54, -4.7, -2.8, -4.32, -4.51, -6.8, -8.3, -8.51, -2.6, -4.99, -5.22, -3.6, -4.67, -4.82, -2.81, -3.78, -3.9, -3.04, -5.13, -5.37, 1.55, 0.65, 0.45, 1.95, 1.75, 1.55, 3.55, 2.65, 2.45, 2.35, 1.65, 1.55, 3.85, 3.35, 3.15, 6.15, 5.05, 4.85, 1.35, 0.75, 0.65, 4.55, 3.85, 3.65, 5.55, 4.45, 4.25, 2.05, 1.45, 1.25, 350.0, 350.0, 350.0, 283.0, 283.0, 283.0, 338.0, 338.0, 338.0, 436.0, 436.0, 436.0, 427.0, 427.0, 427.0, 467.0, 467.0, 467.0, 417.0, 417.0, 417.0, 330.0, 330.0, 330.0, 347.0, 347.0, 347.0, 275.0, 275.0, 275.0], 'windpower': [163.18, 145.31, 147.89, 164.91, 152.32, 131.29, 141.36, 138.3, 137.56, 150.26, 163.91, 160.07]}

In [157]:
search_index_model = SearchIndexModel(
  definition={
    "fields": [
      {
        "type": "vector",
        "numDimensions": 720,
        "path": "vectors",
        "similarity": "cosine"
      }
    ]
  },
  name="wind_power_vector_index",
  type="vectorSearch"
)

In [159]:
result = coll.create_search_index(model=search_index_model)
print("New search index named " + result + " is building.")

New search index named wind_power_vector_index is building.